### ISSUE TITLE
Research Electron testing practices

### ISSUE THREAD

**Issue by nugmanoff** [crococoders/chaikovsky#11]
Due to the fact that we want to (at least try to) write cleaner code we need to write tests.
Goals is to research & review general JS/TS testing approaches and frameworks. Then look specifically for testing Electron apps.

• You might take a look at TDD, BDD - maybe we will decide to adopt them if we feel so.
• Also you might take a look at Snapshot testing and whether or not it is useful for Electron and how to do it (if it is possible)

• https://www.electronjs.org/docs/development/testing
• https://github.com/mawrkus/js-unit-testing-guide
• https://jestjs.io/
• https://mochajs.org/
• https://www.chaijs.com/

**Comment by yerkeboolean** [comment]
I made some research and noticed that some popular projects don't use test frameworks.
Instead of that they use linters like [typescript](https://www.typescriptlang.org/index.html), [XO](https://github.com/xojs/xo), [StandardJS](https://github.com/standard), [Stylelint](https://stylelint.io/)

[Carpine - 5.3k stars](https://github.com/sindresorhus/caprine)
[Git-it - 3.3k stars](https://github.com/jlord/git-it-electron)
[WebTorrent - 7.7k start](https://github.com/webtorrent/webtorrent-desktop) - here for integration testing used spectron, but main test is linting, too

**Comment by nugmanoff** [comment]
@yerkeboolean ok, gotcha!
But I think we shouldn't focus on popular Electron projects then.

We will certainly need Spectron for integration tests, as you stated, but also we need some testing + matching framework for writing simple unit tests. Due to the fact that most of our code is going to be React and pure JS + TS, you should research that way.

You should basically treat our project as React + JS/TS, and look for practices used there (there are plenty of them, I am sure). We discovered Electron and that's ok for Electron-specific integration tests, but we need to cover all of our other React code (which is going to be like 95% of the project) with tests as well. So I think you are being just a little misdirected here :)

**Comment by yerkeboolean** [comment]
I think we should use [Jest(30k stars)](https://github.com/facebook/jest) because it recommended in [React Docs](https://reactjs.org/docs/testing.html) you can access DOM via jsdom
There is also [React Testing Library(11k stars)](https://github.com/testing-library/react-testing-library) it is more simpler but has less features.

[Here ](https://stackshare.io/stackups/jasmine-vs-jest-vs-mocha) is comparison Jasmine - Jest - Mocha 

Why I don't want to use [Mocha ](https://mochajs.org/) because it is hard to configurate, even it is most popular and most used framework


https://jestjs.io/en/
https://github.com/sapegin/jest-cheat-sheet
https://github.com/infinitered/awesome-react-testing

What gives [Jest ](https://jestjs.io/) to us: 
- Easy configuration 
- It was made for React by Facebook, they match perfectly
- We can use it with TypeScript through Babel
- Has [Snapshot testing](https://jestjs.io/docs/en/snapshot-testing).
- It was developed especially for React and it has features like get state and match it with snapshots 	
- [DDT](https://github.com/sapegin/jest-cheat-sheet#data-driven-tests-jest-23)


There is also [Enzyme ](https://enzymejs.github.io/enzyme/) -  Testing utility for React that makes it easier to test your React Components' output.
Enzyme's API is meant to be intuitive and flexible by mimicking jQuery's API for DOM manipulation and traversal.
It means that you can get Component that needed to be tested by Selector 
- Enzyme allows to write unit tests using regular assertions.
- It allows to write integration tests using rendered components. Read [here ](https://enzymejs.github.io/enzyme/docs/api/)

If we will going to try e2e testing best choice is Cypress 


https://medium.com/codeclan/testing-react-with-jest-and-enzyme-20505fec4675
https://codeburst.io/testing-react-events-with-jest-and-enzyme-ii-46fbe4b8b589

https://blog.sapegin.me/all/react-testing-1-best-practices/
https://blog.sapegin.me/all/react-testing-2-jest-and-enzyme/

https://www.toptal.com/qa/how-to-write-testable-code-and-why-it-matters
