### ISSUE TITLE
Research Electron development environment

### ISSUE THREAD

**Issue by nugmanoff** [crococoders/chaikovsky#8]
Aim is to research everything we need to know about Electron development as thoroughly as possible. Some key points to consider are:

- How it works under the hood
- Build (distribution) process
- Application architecture
- CLIs to manage the development process & boilerplate generation
- Main process modules
- Pitfalls & caveats to consider 

We can basically find everything we need in [official Electron docs](https://www.electronjs.org/docs)

Feel free to post here any relevant articles and guides that can help us understand Electron development in more detail or it can just be some important excerpts and points from Electron docs.

**Comment by yerkeboolean** [comment]
This article is pretty interesting, there listed advantages of Electron and explains how it works by short example
https://www.alibabacloud.com/blog/what-is-electronjs-and-why-should-we-use-it_581971

Here some useful info if you can't still get what means process renderer and main renderer
https://www.freecodecamp.org/news/how-to-build-your-first-app-with-electron-41ebdb796930/

If we will create our enviroment  without [Electron-forge](https://www.electronforge.io/) (because it has in-built) or other tools we should add [Electron-packager](https://github.com/electron/electron-packager) for bundle our app, many tutorials miss this.

Here many useful tips, pitfalls and caveats to consider:

- https://blog.avocode.com/4-must-know-tips-for-building-cross-platform-electron-apps-f3ae9c2bffff
- https://medium.com/@michaljurkowski/what-you-should-know-before-you-start-using-electron-js-the-beginners-tips-6ba3b8d5c2e0
